identifier = "pu"
name = "Project Utils"
description = "Build, test and management tools for any language."
version = "0.0.0-a.0" # Stricter https://semver.org/; /^(?'major'(?'number'[1-9]\d*|0))\.(?'minor'(?&number))\.(?'patch'(?&number))(?:-(?'preReleaseIdentifier'[a-z])\.(?'preReleaseNumber'(?&number)))?$/gm
license = "LGPL-3.0-only" # SPDX identifier

[organization]
  identifier = "pimous.dev" # Domain name, usually registered.
  name = "Pimous Dev."
  url = "https://www.pimous.dev/"
  note = "A development studio of open-source, free and environmentally friendly librairies, softwares, and game servers."

[author.Xibitol]
	name = "Xibitol"
	url = "https://www.github.com/Xibitol"
	note = "A developer in too many domains."
	roles = ["Developer", "DevOps"]

[projects]
	[projects.main]
		description = "Main program containing all tools."
		language = "c"
		type = "executable"
		[projects.main.dependencies]
			c = "=23"
			putils = "subproject"
			libtoml = ">=1.4.0"
			libcdir = "static=2.6.0"
	[projects.jutils]
		description = "Utilities for any java program."
		language = "java"
		type = "library"
		[projects.jutils.dependencies]
			java = "=21"