set(PUCUTILS_TEST_LIB_OUTPUT_DIR "${SUBPROJECT_TEST_OUTPUT_DIR}/lib/pu")
set(PUCUTILS_TEST_INCLUDE_OUTPUT_DIR "${SUBPROJECT_TEST_OUTPUT_DIR}/include")

getSources(SOURCES puctest "${SOURCE_DIR}")
getPrivateHeaders(PRIVATE_HEADERS puctest "${SOURCE_DIR}")
getPublicHeaders(PUBLIC_HEADERS puctest "${SOURCE_DIR}")

# TARGETS
add_library(puctest SHARED)
target_sources(puctest
	PRIVATE "${SOURCES}" "${PRIVATE_HEADERS}"
	PUBLIC "${PUBLIC_HEADERS}"
)
set_target_properties(puctest PROPERTIES
	COMPILE_FLAGS "-D PUCTEST_COMPILATION"
	LIBRARY_OUTPUT_DIRECTORY "${PUCUTILS_TEST_LIB_OUTPUT_DIR}"
)